### ISSUE TITLE
Please create 10 branch for kanban_open_project

### ISSUE THREAD

**Issue by m3dbedb** [ingadhoc/project#38]
Module kanban_open_project for odoo 9 works with odoo 10

**Comment by jjscarafia** [comment]
Sorry but we are going to make 10.0 branchs only after july (moreless) as we are working in v9 yet ant once opened we need to keep them syncked

**Comment by m3dbedb** [comment]
Here is translation to russian for module project_stage
[ru.zip](https://github.com/ingadhoc/project/files/899803/ru.zip)

**Comment by jjscarafia** [comment]
Hi! I've added the translation. For the next time, the correct place for translations is [transifex](https://www.transifex.com/adhoc/).
Thanks!
